#!/usr/bin/env ruby

# Splash Screen Style Website
# ===========================
#
# ## DESCRIPTION
#
# This WebME template provides a simple splash-screen style, README
# and GEM DO POM based project website layout.
#
# ## ARGUMENTS
#
#   * `directory`:
#     Directory relative to output option to put website files.
#     By default looks for `site`, `website`, `web` or `www`.
#     If not found, it creates a new `site` directory. To generate
#     the template in the current directory, use the dot-path, `.`.
#
# ## COPYRIGHT
#
# WebMe is Copyright (C) 2008 Thomas Sawyer <http://trans.github.com/>
#
# ## SEE ALSO
#
# sow(1), sow-webme(1)

copy '**/*'

