--- !ruby/object:RDoc::RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:RDoc::Markup::Flow::P 
  body: Load config file.
full_name: WebMe#load_config
is_singleton: false
name: load_config
params: ()
visibility: public
