#!/usr/bin/env ruby

utilize 'gemdo'
utilize 'color'

require 'gemdo/readme'

argument :site

let :site, (output.glob('{site,website,web,www}').first || 'site')

key = data.title
hue = data.fg ? color(data.fg) : color_from_keyword(key)

if hue.brightness > 0.5
  set :fg, hue.html
  set :bg, hue.adjust_brightness(-50).html
  set :hg, hue.adjust_brightness(-30).html
  set :lg, hue.adjust_brightness(+30).html
else
  set :fg, hue.html
  set :bg, hue.adjust_brightness(+50).html
  set :hg, hue.adjust_brightness(+30).html
  set :lg, hue.adjust_brightness(-30).html
end

let :font, 'sans serif'
let :size, '1em'

text = project.readme.text
type = project.readme.extname.sub(/^\./,'')

i = text.index(/^(==|##)/)

set :header, Malt.render(:text=>text[0...i],  :type=>type)
set :body,   Malt.render(:text=>text[i...-1], :type=>type)

rsrc = project.profile.resources
link = rsrc['download'] || rsrc['gem']

set :link, link

